name: Deployment Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup PHP 8.5 (stable)
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.5'
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Copy .env File
        run: |
            cp .env.example .env
      - name: Generate Application Key
        run: |
          php artisan key:generate
      - name: Run unit tests
        run: |
            php artisan test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: library-api
           MYSQL_USER: appuser
           MYSQL_PASSWORD: apppass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.5 (stable)
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.5'

      - name: Copy .env File
        env:
            DB_DATABASE: library-api
            DB_USERNAME: apppass
            DB_PASSWORD: apppass
        run: |
            cp .env.example .env
            sed -i 's/DB_DATABASE=.*/DB_DATABASE='"$DB_DATABASE"'/' .env
            sed -i 's/DB_USERNAME=/DB_USERNAME='"$DB_USERNAME"'/' .env
            sed -i 's/DB_PASSWORD=/DB_PASSWORD='"$DB_PASSWORD"'/' .env

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate Application Key
        run: |
          php artisan key:generate

      - name: Run Migrations & Seeds
        run: |
            php artisan migrate --force
            php artisan db:seed --force
