name: Deployment Workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.5 (stable)
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.5'

      - name: Start MySQL Service
        run: |
            sudo systemctl start mysql

      - name: Configure MySQL
        run: |
            sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'; FLUSH PRIVILEGES;"
            mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS library_system_test;"

      - name: Copy .env File
        run: |
            cp .env.example .env
            sed -i 's/DB_DATABASE=.*/DB_DATABASE=library_system_test/' .env
            sed -i 's/DB_USERNAME=/DB_USERNAME=root/' .env
            sed -i 's/DB_PASSWORD=/DB_PASSWORD=root/' .env

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate Application Key
        run: |
          php artisan key:generate

      - name: Run Migrations & Seeds
        run: |
            php artisan migrate --force
            php artisan db:seed --force
      - name: Run unit tests
        run: |
            php artisan test --testsuite=Unit
